### ISSUE TITLE
FlipView manipulation and animation

### ISSUE THREAD

**Issue by Nekroido** [Kinnara/WPToolkit#12]
FlipView captures all manipulation events and cancels vertical swipes/flicks/drags, so I'm unable to scroll the ScrollViewer.
It also has no animation transition with updating the SelectedIndex property (though the feature seems to be present as per source code).

**Comment by Kinnara** [comment]
Directly controlling the ScrollViewer is not supported by the current implementation.

Please try the latest code and sample to check if the second issue still exists.
