### ISSUE TITLE
ElementScrollingHost,  ElementItemsPresenter are getting null

### ISSUE THREAD

**Issue by pallammadhukar** [Kinnara/WPToolkit#14]
Hi, i copied all FlipView Control of your toolkit into my project. I have debugged both your sample and my sample i am getting 
ElementScrollingHost =null
ElementItemsPresenter=null
In your sample your able to get. 

Below method your where your assigned values:

public override void OnApplyTemplate()
        {
            _animator = null;
            ItemsHost = null;
            ItemsHostSize = new Size(double.NaN, double.NaN);

```
        if (ElementItemsPresenter != null)
        {
            LayoutUpdated -= OnLayoutUpdated;
        }

        base.OnApplyTemplate();

        ElementScrollingHost = GetTemplateChild(ElementScrollingHostName) as ScrollViewer;
        ElementItemsPresenter = GetTemplateChild(ElementItemsPresenterName) as ItemsPresenter;

        if (ElementItemsPresenter != null)
        {
            InitializeItemsHost();

            if (ItemsHost == null)
            {
                LayoutUpdated += OnLayoutUpdated;
            }
        }
    }
```

I am not getting why those values are null. sample running without error. but i am getting following output:
![output](https://f.cloud.github.com/assets/3232745/2205707/4ce8e954-9954-11e3-80f9-6815163a6e01.png)

**Comment by Kinnara** [comment]
You need to include the default style in generic.xaml as well.

**Comment by pallammadhukar** [comment]
thanks. it worked perfectly.
