### ISSUE TITLE
[feature need]when will support multi-touch ?

### ISSUE THREAD

**Issue by tfzxyinhao** [Kinnara/WPToolkit#15]
when will support multi-touch ?
I think this feature can bring good Interactive to app

**Comment by Kinnara** [comment]
Could you elaborate on what it means to support multi-touch?

**Comment by tfzxyinhao** [comment]
gesture,can detect more then two finger hold and move.

**Comment by Kinnara** [comment]
Since standard Windows Phone touch gestures do not require more than two touch points, I think this library is not the best fit for the requested feature.
