### ISSUE TITLE
PhoneTextBox is missing Hint property

### ISSUE THREAD

**Issue by Depechie** [Kinnara/WPToolkit#18]
There is no Hint property on the PhoneTextBox control like on the original WPToolkit one... http://phone.codeplex.com/SourceControl/latest#Microsoft.Phone.Controls.Toolkit/PhoneTextBox/PhoneTextBox.cs

**Comment by Kinnara** [comment]
It has the PlaceholderText property, like the WinRT TextBox.

**Comment by Depechie** [comment]
I missed that, thanks for the head up!!
