### ISSUE TITLE
Cannot run PhoneToolkitSample.WP8 project

### ISSUE THREAD

**Issue by prgrmRyC** [Kinnara/WPToolkit#9]
Your LIB looks cool and I wanted to test it out, but I cannot get the samples to compile and run for windows phone 8.  I tried opening just the windows phone 8 samples project, but it loaded everything anyway (including the WP7 stuff).

Here are the error I am getting when trying to run it on the WP8 emulator on my WIn 8 Pro 64 bit system with VS 2013.

Warning 1   Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. Microsoft.Phone.Controls.Toolkit.WP7
Error   2   An assembly with the same identity 'System.IO, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references. c:\Users\Ryan\SkyDrive\Programming\WinPhone\WPToolkit-custom\WPToolkit-custom\packages\Microsoft.Bcl.1.1.3\lib\sl4-windowsphone71\System.IO.dll Microsoft.Phone.Controls.Toolkit.WP7
Error   3   An assembly with the same identity 'System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.    c:\Users\Ryan\SkyDrive\Programming\WinPhone\WPToolkit-custom\WPToolkit-custom\packages\Microsoft.Bcl.1.1.3\lib\sl4-windowsphone71\System.Runtime.dll    Microsoft.Phone.Controls.Toolkit.WP7
Error   4   An assembly with the same identity 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.    c:\Users\Ryan\SkyDrive\Programming\WinPhone\WPToolkit-custom\WPToolkit-custom\packages\Microsoft.Bcl.1.1.3\lib\sl4-windowsphone71\System.Threading.Tasks.dll    Microsoft.Phone.Controls.Toolkit.WP7
Warning 5   Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. PhoneToolkitSample.WP7
Error   6   Metadata file 'C:\Users\Ryan\SkyDrive\Programming\WinPhone\WPToolkit-custom\WPToolkit-custom\Bin\WP7\Debug\Microsoft.Phone.Controls.Toolkit.dll' could not be found C:\Users\Ryan\SkyDrive\Programming\WinPhone\WPToolkit-custom\WPToolkit-custom\PhoneToolkitSample\CSC    PhoneToolkitSample.WP7

-=Ryan

**Comment by Kinnara** [comment]
VS 2013 does not support WP7 so it upgraded the WP7 projects to WP8, but not the NuGet packages. Try unloading the WP7 projects and using only the WP8 projects.

**Comment by prgrmRyC** [comment]
Removing all the WP7 projects and references worked.  Thanks!

**Comment by prgrmRyC** [comment]
Kinnara,

Why am I getting this exception trying to view the ExpanderViewSample.xaml?

See attached screen shot

Thanks

-=Ryan

**Comment by Kinnara** [comment]
Hi Ryan,

There is no screenshot attached.

**Comment by prgrmRyC** [comment]
Hmmm github mail must have removed it and I see no way to attach one to a post. 

-=Ryan
